import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '../lib/utils';
import ThemedStyle from '@/assets/styles/themed-style';
import AntdTheme from '@/layouts/shared/theme/antd-theme';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.variable, 'min-h-screen font-sans antialiased')}
      >
        <ThemedStyle />
        <AntdTheme>{children}</AntdTheme>
      </body>
    </html>
  );
}
