import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '../lib/utils';
import ThemedStyle from '@/client/assets/styles/themed-style';
import ThemeProvider from '@/client/layouts/shared/theme/theme-provider';
import TrpcProvider from '@/client/store/services/trpc-provider';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Nextjs Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(inter.variable, 'min-h-screen font-sans antialiased')}
      >
        <TrpcProvider>
          <ThemedStyle />
          <ThemeProvider>{children}</ThemeProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
